[package]
name = "jwt_example"
type = "bin"
compiler_version = ">=1.0.0"

[dependencies]
bignum = {tag = "v0.5.0", git = "https://github.com/noir-lang/noir-bignum"}
noir_rsa_pss = { path = "../../noir_rsa_pss/lib" } 